version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  webserver:
    build: webserver
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./webserver:/var/www/html

  flask:
    build: './flask'
    container_name: flask
    restart: unless-stopped
    ports:
      - 5000:5000 # test port
      # - 8080:8080 # prod port 
    volumes:
      - ./flask:/src
    environment:
      - STAGE=dev

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    restart: unless-stopped
