version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  webserver:
    build: webserver
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./webserver:/var/www/html
